README.md
lib/resty/openidc.lua

There are 2 commits:
* The first is just white-space trims, no code change was introduced
* The second commit makes the change

Issue/35 Use exp for TTL cache control

---

lib/resty/openidc.lua

ngx.time() uses a cached value associated with the request to
represent time, which is more efficient than os.time() (which
requires an additional syscall).

User ngx.time() in place of os.time()

---

README.md
lib/resty/openidc.lua

Not sure this is ok in all cases. E.g. when no post_logout_redirect_uri  is configured. Unfortunately I don't have sufficient infrastructure to test that.

Adding token hint to op logout request

---

lib/resty/openidc.lua

Applying iat_slack also to openidc.jwt_verify

---

lib/resty/openidc.lua

This fixes the problem described by #69 - which I just stumbled upon myself :-)
The changes are very similar to #72 
/cc @nielsole

properly deal with ngx.redirect's return value

---

README.md

This patch applies better access block for Google+ example.
Signed-off-by: Zabielski, Kamil <kamil.zabielski@outlook.com>

Refactor Google+ singin code

---

lib/resty/openidc.lua

* ignore any configured `token_endpoint_auth_method` that the library doesn't support (and log an error)
* fall back to the first `oken_endpoint_auth_methods_supported` the library can use
fixes #95

fiter token_auth_methods by those actually supported

---

lib/resty/openidc.lua

this is a combination of minor function extractions, and few changes suggested by luacheck including removal of dead code, whitespace cleanup and shadowing of variables.
It is probably easier to look through the commits individually rather than the whole change.
560285a has been detected by luacheck, so I'm glad I gave it a try :-)

Small cleanups

---

ChangeLog
lib/resty/openidc.lua
tests/spec/introspection_spec.lua

see https://github.com/pingidentity/lua-resty-openidc/commit/1e2d705708531a5e584a612391243cf6bf324840#commitcomment-25265312

only accept active tokens in introspect

---

ChangeLog
lib/resty/openidc.lua
tests/spec/bearer_token_verification_spec.lua
tests/spec/id_token_validation_spec.lua
tests/spec/test_support.lua

Hmac signature support for id tokens

---

ChangeLog
lib/resty/openidc.lua
tests/spec/redirect_to_op_spec.lua
tests/spec/test_support.lua

use X-Forwarded-Host when building redir uri if present

---

lib/resty/openidc.lua
tests/spec/redirect_to_op_spec.lua

add support for "Forwarded" header field - RFC7239

---

lib/resty/openidc.lua

Let’s keep it simple for my first contribution to this project :P
I’ve deployed `lua-resty-openidc` a couple of time now, and I realized that I was lacking some key logs to understand why the current configuration I setup was not working properly. Indeed, there are many logs related to the discovery endpoint or to the authentication method on the token endpoint… but nothing really useful to understand where we are in the overall OpenID Connect process.
This (simple!) PR consequently intends to add these logs to trace the key steps of the authentication process, for a better debugging to make the deployment configuration work.

Adding usefull logs for debug or during configuration setup

---

README.md
lib/resty/openidc.lua

Need to expose log setter via module function

---

lib/resty/openidc.lua

Tab - 2 chars
Indent - 2 chars
Continuation indent - 4 chars
Don't keep indent on empty lines

There are no functional changes here except for code format

---

lib/resty/openidc.lua

Authentication path is hugely suboptimal when session exists and valid

---

ChangeLog
README.md
lib/resty/openidc.lua
tests/spec/bearer_token_verification_spec.lua

Signed-off-by: Hans Zandbelt <hans.zandbelt@zmartzone.eu>

merge commit earlier key confusion branch that was messed up

---

ChangeLog
lib/resty/openidc.lua

create a new session id when the token has been refreshed

---

lib/resty/openidc.lua

nul -> nil for openidc_get_bearer_access_token_from_cookie method

---

lib/resty/openidc.lua

Make sure err is a local variable

---

lua-resty-openidc-1.7.2-1.rockspec

Fixed https://github.com/zmartzone/lua-resty-openidc/issues/326

fix: Failed installing dependency: lua-resty-jwt-0.2.2-0

---

lib/resty/openidc.lua

#404 Possibilty to pass in a existing session

---

ChangeLog
README.md
lib/resty/openidc.lua
tests/spec/form_post_spec.lua

Support form post response mode

---

README.md

The current documentation describes configuration for lua-resty-session version 3 only.
Naively following the default installation steps will set up lua-resty-session version 4, and the session cookie storage configuration is different. This README change demonstrates the version 4 configuration isntead.
I have also removed a broken link in the current documentation; the link used to point to the README for lua-resty-session v3, and the v4 README no longer has the section that was linked to.
This updated configuration should also provide a way answer to several outstanding questions in the GitHub issues, e.g. https://github.com/zmartzone/lua-resty-openidc/issues/502 and https://github.com/zmartzone/lua-resty-openidc/issues/514

Update documentation for configuration of lua-resty-session v4
