- lib/resty/openidc.lua
- allows a TLS offload agent to forward the scheme
> scheme to be derived

- lib/resty/openidc.lua
The current code uses client_secret_post - sending the client ID and secret in the POST body when communicating with the OP. I needed to test with an OP that only supports client_secret_basic so I added a new config option to allow for either mechanism to be used.
To do that I needed to pass the config changes into openidc_call_token_endpoint - I wound up passing "opts" in as a new first argument. That change allowed me to remove the 3rd argument (ssl_verify) argument since that value is already in opts.
If client_authentication_mode option is omitted in nginx.conf then my code will use the first value in the metadata.
Please let me know if you want me to do this in a different way.
> Added option client_authentication_mode.

- lib/resty/openidc.lua
Not all OpenID Connect providers supply the userinfo endpoint (e.g. [dex](https://github.com/coreos/dex/)). This is according to [spec](https://openid.net/specs/openid-connect-discovery-_0.html#ProviderMetadata):
```
userinfo_endpoint
RECOMMENDED. URL of the OP's UserInfo Endpoint [OpenID.Core]. This URL MUST use the https scheme and MAY contain port, path, and query parameter components.
```
> Fix crash when userinfo_endpoint is not set

- lib/resty/openidc.lua
- Removed unneccessary initializers
- added some locals
- fixed some global variable leaks
- adjusted session to only start when it is modified (in hopes to fix locking problems)
> Trying to fix session locking problems on some server side storages

- .travis.yml
- .travis/platform.sh
- .travis/setenv_lua.sh
- .travis/setup_lua.sh
This PR adds a [Travis build](https://travis-ci.org/asbjornu/lua-resty-openidc) to the project so the `.rockspec` is automatically built and uploaded to [LuaRocks](https://luarocks.org/modules/asbjornu/lua-resty-openidc) on every commit. Before merging this:
- @ping-identity's [Travis build for this repository](https://travis-ci.org/pingidentity/lua-resty-openidc) should be enabled. The one I link to above is my personal Travis project.
- Someone affiliated with @ping-identity should create a LuaRocks profile and get an API key from [the settings page](https://luarocks.org/settings/api-keys), so the rock is uploaded to a more "official" profile. The currently uploaded module belongs to my personal account, which isn't ideal.
- This API key must be configured in the [settings of the Travis …
> Add Travis build

- lua-resty-openidc-1.2.0-1.rockspec
When I installed this from a rock, require("resty.openidc") did not work. Instead, it was installed as require("openidc"). This change brings it in line with what lua-resty-jwt and lua-resty-http do.
> install openidc consistent with README

- lib/resty/openidc.lua
This change allows the jwt id_token to be set on the proxied request.  Kubernetes OIDC integration requires the bearer token be set to the jwt id_token instead of the access_token.
> Saving encrypted id_token to session data.

- README.md
- lib/resty/openidc.lua
This patch adds easy verification of jwt tokens, via the JWKS from the discovery endpoint.
Please feel free to leave any suggestions.
> Feature jwt discovery validation

- AUTHORS
- README.md
- lib/resty/openidc.lua
Hi,
these are 3 patches that we use at Mozilla (i.e. for Mozilla properties authenticating with OpenID Connect) with OpenID Connect. Let me know if you'd prefer 3 PRs, though some depend on each other.
The prompt parameter allows for silent re authentication in particular in this case (though this can be further extended later to support all options), as seen on http://testrp.security.allizom.org/. This allows to refresh user profile information without login the user out and back in. Spec at http://openid.net/specs/openid-connect-implicit-1_0.html#RequestParameters
The session data being returned allows for the calling code to get full session data (lua-resty-session does not always allow this otherwise)
Finally, the logout URL redirect allows to override the discovered redirect from the …
> Support for prompt parameter during authorization, returning session data, and logout url override

- README.md
- lib/resty/openidc.lua
PR  for issue #51 
Hope this PR is fine (this is my first attempt with lua)
Access token renewal when access_token is expired by calling token endpoint with grant_type=refresh_token.
refreshToken must be one of the granted scope for this to happen.
* API `authenticate`  has been updated
Whenever the access_token is expired, we renew the access_token if refresh_token exist.
* API `access_token` has been added
This API returns a valid access_token (either the existing one if it's not expired, a renewed one if it was expired or nil if there's no access_token or no way to get a valid access_token). 
This API can be used to map a /api to OAuth protected Resource Servers in case we don't want to trigger authentication on /api.
We can imagine this kind of usage when Resource Server are called by …
> Access token renewal on expiration

- AUTHORS
- ChangeLog
- lib/resty/openidc.lua
Closes #56 
I didn't add anything to the README for this new feature as it didn't look like there was yet a section that calls out how to call the authenticate method.
> Add support for passing resty.session options

- lib/resty/openidc.lua
I've got an API where clients can provide an access_token either as a bearer token or using a different channel. Using that I may be calling `openidc.jwt_verify` multiple times using the same options.
The trivial patch adds the same guard to `openidc.jwt_verify` that's already present in `openidc.authenticate`.
> guard call to openidc_discover against repeated use

- lib/resty/openidc.lua
With this patch the caller gets access to the unparsed bearer token and doesn't have to parse the Authorization header by itself again.
> return the raw bearer token from `openidc.bearer_jwt_verify`

- lib/resty/openidc.lua
When verifying a JWT or a Bearer token currently only the `nbf` and `exp` claims are checked as this is the default. I'd like to also verify things like `iss` and maybe `aud`. Allowing callers to provide the claim specs seemed to be the easiest approach.
> allow optional claim specs when verifying JWT access tokens

- lib/resty/openidc.lua
Make sure openidc_discover is called before
refreshing the accessToken.
Otherwise, we'll get an error since token endpoint
url will be nil.
> access_token API: error refreshing token

- README.md
- lib/resty/openidc.lua
This adds an option to forcefully re-run the code grant flow. My use case is adding additional scopes after a user has already authenticated.
> add option that forces the auth flow to be executed

- README.md
Fixing example of #65 - see https://github.com/pingidentity/lua-resty-openidc/pull/65#pullrequestreview-41646227
> make force_reauthorize example use default value

- lib/resty/openidc.lua
I got a error like as blow:
```
2017/06/30 08:24:01 [error] 7#7: *15 lua entry thread aborted: runtime error: /usr/local/lib/lua/5.1/resty/openidc.lua:69: bad argument #3 to 'set' (number expected, got nil)
```
It's because keycloak return `{"active":false}` when pass a invalid token.
> fix set cache when pass an invalid token to keycloak

- lib/resty/openidc.lua
Fix for redirect_after_logout_with_id_token_hint options
> missed opts prefix for token hint option

- lib/resty/openidc.lua
Adds support for the `display` request parameter in accordance with the [OIDC spec 3.1.2.1](http://openid.net/specs/openid-connect-core-1_0.html#rfc.section.3.1.2.1).
> Support display parameter

- README.md
This patch fixes default configuration for Google+.
* Fix path for CA.
For most systems, path `/opt/local/etc/openssl/cert.pem` does not exist.
If someone will be interested in modifying CA, he will be able to do so.
* `'` charactes in comments case emergency error in nginx.
* Remove trailing spaces.
Signed-off-by: Zabielski, Kamil <kamil.zabielski@outlook.com>
> Fix default Google+ Sign-up configuration

- README.md
- lib/resty/openidc.lua
These commits introduce feature flags, which allow configuration of what features are enabled. e.g. retrieving the user info, or storing the access_key or encrypted id_token.
This includes PR #86.
We are dependent on keeping the session size small as we store it in a cookie for easier operations and the current sessions size is about 6kb which is prohibitive, e.g. webservers like nginx, jetty and tomcat can't deal with large headers. Also they get transfered on every request.
This PR also superseeds #73. Feedback is very welcome.
> Feature flags

- lib/resty/openidc.lua
- tests/Dockerfile
- tests/spec/id_token_validation_spec.lua
* fix the log message for old `iat` claim
* apply slack to `exp` claim consistently
* explicitly verify the presence of the `aud` and `exp` claims
> Id token verification issues

- lib/resty/openidc.lua
- tests/spec/bearer_token_verification_spec.lua
- tests/spec/test_support.lua
if you don't specify any custom "claim specs" lua-resty-jwt will add verifications for the `exp` and `nbf` claims if the JWT contains them[1][2]. These checks need to know about the configured slack value as lua-resty-jwt 's default is a slack of 0[3].
I also fixed an error for the case where the access token doesn't contain any `exp` claim at all.
[1] https://github.com/SkyLothar/lua-resty-jwt/blob/master/lib/resty/jwt.lua#L680
[2] https://github.com/SkyLothar/lua-resty-jwt/blob/master/lib/resty/jwt.lua#L359
[3] https://github.com/SkyLothar/lua-resty-jwt/blob/master/lib/resty/jwt-validators.lua#L320
> Make jwt exp check use slack

- lib/resty/openidc.lua
- tests/spec/bearer_token_verification_spec.lua
search explicitly for RSA keys as that's the only type of key that we support today; this way other keys won't get in the way in case a JWT was provided with no kid: if there's only one RSA (signing) key amongst the set we can still assume that's the one we need
> Differentiate rsa keys

- README.md
- lib/resty/openidc.lua
also provide "jwks" cache dictionary sample in README.md to prevent
repetated lookups
Signed-off-by: Hans Zandbelt <hans.zandbelt@zmartzone.eu>
> support key rollover for JWKs pulled from jwks_uri

- ChangeLog
- lib/resty/openidc.lua
- tests/spec/logout_spec.lua
currently the `id_token_hint` parameter is added to `opts.redirect_after_logout_uri` separated by a `&` unconditionally.
> ensure id_token_hint uses correct separator on logout

- ChangeLog
- lib/resty/openidc.lua
- tests/spec/logout_spec.lua
if the id_token has been cached, that is. Also fixes the case for
redirect_after_logout_uri if caching of the id_token has been
disabled.
> add id_token_hint to end_session_endpoint

- ChangeLog
- lib/resty/openidc.lua
- tests/spec/access_token_access_spec.lua
- tests/spec/bearer_token_verification_spec.lua
- tests/spec/introspection_spec.lua
- tests/spec/redirect_to_op_spec.lua
- tests/spec/token_request_spec.lua
- tests/spec/userinfo_spec.lua
This PR contains some improvements to error logging but most importantly it uses `cjson.safe` when parsing the endpoints' JSON responses. Our code expects `decode` to return `nil` on errors which is exactly what `cjson.safe` does, but `cjson` raises an error instead.
The change assumes we'll find cjson 2.1.0 (released in 2012) - if this is not acceptable, I can rework the change to use `pcall` instead.
> Improve json error handling

- ChangeLog
- README.md
- lib/resty/openidc.lua
- tests/spec/access_token_access_spec.lua
- tests/spec/bearer_token_verification_spec.lua
- tests/spec/introspection_spec.lua
- tests/spec/redirect_to_op_spec.lua
- tests/spec/test_support.lua
- tests/spec/token_request_spec.lua
- tests/spec/userinfo_spec.lua
I'm not really sure whether the extra convenience of `timeout=1000` is really needed of the table version, but wanted to mirror the options available for lua-resty-http.
> add configurable timeouts for http calls

- ChangeLog
- README.md
- lib/resty/openidc.lua
- tests/spec/test_support.lua
- tests/spec/token_refresh_spec.lua
closes #117 
With this patch if we know the token is expired and we fail to refresh it the user will be sent to the authorization endpoint.
While looking through the code I realized that if we know the user has authenticated once (`session.data.authenticated` is true) but don't store the access token because of `store_in_session` settings then all requests will be allowed as long as the session exists. I'm not sure this is intended.
> let user re-authenticate if we know the access token has expired

- lib/resty/openidc.lua
This is an alternative solution for #119
> leave opts alone when silently re-authenticating

- README.md
- lib/resty/openidc.lua
Hello,
This is a pull request to fix the zmartzone/lua-resty-openidc#45 issue. I'm a lua beginner so my implementation could be naïve. It's work with my use case so I propose my fix to the project : 
* Naïve implementation works with OpendId Connect Authorization
Code Flow
* Add proxy_opts table to the opts, with two values :
- http_proxy (in curl format : http://<proxy_host>:<proxy_port>/)
- https_proxy (in curl format : http://<proxy_host>:<proxy_port>/)
> Fix zmartzone/lua-resty-openidc#45 : Add outgoing proxy support

- lib/resty/openidc.lua
To implement some additional behavior on top of `lua-resty-openidc` library, it is sometimes required to get access to the Discovery Endpoint data.
Instead of re-implementing the overall mechanism to get and cache the discovery data, let's open the corresponding function as public.
> Adding public function to get Discovery Endpoint data

- ChangeLog
- lib/resty/openidc.lua
A time to live in the server caches for the data retrieved from Discovery and JWKS endpoints is defined (1day). This is good as it enables implementing some specific use cases such as key rotation.
However, it might be required to invalidate the caches immediately, in order an update of the OP to be taken into account immediately, for example.
This PR provide the functions (one internal, and one external) to enable a `lua-resty-openidc` client code to trigger the caches invalidation. Discovery and JWKS, caches are flushed, but also introspection as it is better to re-evaluate tokens as the jwks and discovery data may have changed.
> Adding functions to invalidate the various caches

- README.md
Update doc to reflect JWKS validation behavior when x5c isn't present but module and exponent are
> Update doc to reflect JWKS validation behavior when x5c isn't present but module and exponent are

- ChangeLog
- lib/resty/openidc.lua
Hello to all of you,
Several issues were raised for “rare” use case of failed verification of Tokens signatures, resulting in a strange error message saying “too long”: here, in `lua-resty-openidc` project (https://github.com/zmartzone/lua-resty-openidc/issues/135), but also in the `lua-restu-jwt` library used by `lua-resty-openidc` when performing the verification of the Token: https://github.com/SkyLothar/lua-resty-jwt/issues/72
My initial thought (as explained in https://github.com/SkyLothar/lua-resty-jwt/issues/72) was that the issue was at very low level, when running the signature verification computation… but indeed it is not: the issue is in the `lua-restu-openidc` processing, when re-building the Public Key from the data obtained from the JWKS endpoint, in case the key is …
> Token signature verification error "too long" in case public key starts by 0x80

- ChangeLog
- README.md
- lib/resty/openidc.lua
- added support for introspection interval
- added support for passing request cookies on introspection call
- added passing introspection endpoint authorization method into openidc_call_token_endpoint call
> - added support for passing bearer token as cookie

- ChangeLog
- README.md
- lib/resty/openidc.lua
- tests/spec/bearer_token_verification_spec.lua
- tests/spec/id_token_validation_spec.lua
- tests/spec/test_support.lua
- disabled support for "none" alg tokens introduced with 1.5.2 by default.
If you want to enable it, you will now have to explicitly set the accept_none_alg
option to true.
- id tokens using a signature algorithm not announced by the discovery
endpoint are now rejected.
- you can now specify which signing algorithm you expect a bearer token to
use in order to avoid being tricked into accepting a rogue token signed
with a symmetric key when expecting an asymmetric cypher.
- added an option to reject tokens signed by an algorithm not supported by lua-resty-jwt
> Tighten jwt signature validation

- dist.ini
- lua-resty-openidc-1.5.4-1.rockspec
This should add support for OpenSSL 1.1 with the new fork of https://github.com/SkyLothar/lua-resty-jwt at https://github.com/cdbattags/lua-resty-jwt!
Still very confused that you're using two different versions of `lua-resty-hmac` with OPM version and LuaRocks...
> Update lua-resty-jwt for OpenSSL 1.1

- AUTHORS
- ChangeLog
- README.md
- lib/resty/openidc.lua
Added ability to bypass introspection cache. I found that I needed in certain situations for calls to always introspect the token regardless of whether it is cached or not and not affect the state of cache.
> bypass introspection cache on demand.

- ChangeLog
- README.md
- lib/resty/openidc.lua
- tests/spec/redirect_to_op_spec.lua
needed to deal with broken OpenID Connect providers, closes #193
> add an option to suppress the nonce parameter

- ChangeLog
- README.md
- lib/resty/openidc.lua
- tests/spec/bearer_token_verification_spec.lua
- tests/spec/introspection_spec.lua
- tests/spec/redirect_to_op_spec.lua
- tests/spec/test_support.lua
- tests/spec/token_request_spec.lua
adds an optional decorator function that can be used to tweak the HTTP request when lua-resty-openidc talks to the OP.
One use case is passing on correlation tokens or other tracing information.
> HTTP request decorator

- lib/resty/openidc.lua
* Conform to https://tools.ietf.org/html/rfc6749#section-2.3.1 for Active Directory Federation Services (AD FS) with WIA
* Minor indentation fix
> url-encode the Client ID for the Windows Integrated Authentication (WIA) case

- AUTHORS
- ChangeLog
- README.md
- lib/resty/openidc.lua
- tests/spec/logout_spec.lua
- tests/spec/test_support.lua
Notify the authorization server that previously obtained
refresh and access tokens are no longer needed after logout.
Currently this happens in a completely opportunistic way.
If there is no revocation endpoint supplied, a debug message
will be logged and the logout process continues.
If there is a revocation endpoint supplied but the
authorization server does not respond with
HTTP status code 200, an error message will be logged but
the logout process still continues as if there was no error.
> Revoke refresh_token and access_token on logout

- ChangeLog
- lib/resty/openidc.lua
- tests/spec/token_request_spec.lua
This addresses #238 by not selecting one of the JWT auth methods unless the necessary key material is present.
I've also improved the error message highlighted by @XA21X even though it should be impossible to trigger it now.
> Verify preconditions for jwt auth methods

- ChangeLog
- lib/resty/openidc.lua
session start fails if storage adapter host is not accessible (set $session_storage memcache/redis;)
improved message in logs will be as following:
2019/04/23 08:00:06 [error] 21#21: *1 [lua] openidc.lua:1344: authenticate(): Error starting session: memcache.local could not be resolved (3: Host not found)
instead of current unclear message: attempt to index local 'session' (a nil value)
> added error handling when opening session.

- dist.ini
The `pintsized/lua-resty-http` git repo was [renamed](https://github.com/ledgetech/lua-resty-http/commit/f71e9708a3fd0ff4179d4b0d770c91fcf98d0042#diff-a580a87ff9da14b51504d149be8ecaff) to `ledgetech/lua-resty-http` for the 0.13 release. The repo now also redirects from "pintsized" to "ledgetech" on github.com: https://github.com/pintsized/lua-resty-http
This switches the OPM dependency to the new repo name. Without this, you can't install lua-resty-openidc if you already have the newer `pintsized/lua-resty-http` OPM package installed, due to package conflicts:
```
$ opm get ledgetech/lua-resty-http
* Fetching ledgetech/lua-resty-http  
Downloading https://opm.openresty.org/api/pkg/tarball/ledgetech/lua-resty-http-0.14.opm.tar.gz
% Total    % Received % Xferd  Average Speed   Time    Time …
```
> Allow OPM installation with newer lua-resty-http versions

- AUTHORS
- lib/resty/openidc.lua
Problem: When unauth_action is "pass" and refresh of token fails, e.g. because refresh token has expired, then the session attribute "authenticated" is still true. In this case the request will be passed, although the user is not authenticated.
Setting session.data.authenticated to false and returning an error will allow a client to detect, if the refresh was successful.
> Refresh failed pass

- lib/resty/openidc.lua
Fix for #305, no longer sending back arguments provided in the URI or session details.
> Do not send back URI arguments to prevent XSS

- AUTHORS
- ChangeLog
- README.md
- lib/resty/openidc.lua
- tests/spec/test_support.lua
Hello everyone,
In one of our customers, we use this (amazing) library to behave like a lightweight and fast oidc reverse proxy (deployed as a k8s sidecar along with SPA applications).
To be able to proxy page requests and also ajax requests, we configured the proxy to have two default actions (for non authenticated requests): 
- For ajax requests we deny every request that has failed to **authenticate**
- For page requests we don't specify an action (nil), redirecting to the OP if the requests it's not already logged in
However, after some time we started to notice intermittent failures with the ajax requests. The request failed but the session was valid (so it wasn't because HTTP session expiration, SSO session revoked, etc.).
On the openresty logs we found this error:
`2020/02/06 …
> Ability to disable keepalive

- ChangeLog
- README.md
- lib/resty/openidc.lua
- tests/spec/pkce_spec.lua
- tests/spec/sha2.lua
Initially PKCE has only been used for publci clients but recent security best practices recommend enabling it for confidential clients as well. See also the recent OAuth 2.1 draft https://tools.ietf.org/html/draft-parecki-oauth-v2-1-01
> add optional support for PKCE

- tests/Dockerfile
The `xenial` image is not accessible anymore, returns 404. Instead, I've changed to `bionic` to execute tests inside docker.
> Update test  Dockerfile image

- ChangeLog
- README.md
- lib/resty/openidc.lua
closes #399 
If you've got two differently configured locations the cache may allow tokens accepted by one location to be used at a different one - even if they would not be valid for the other location's configuration.
This PR does three things:
* separate the caches for JWT verification and token introspection
* use some of the configuration settings of opts as part of the cache key. I later realized this is probably futile so I added explicit configuration via the third step
* adds an option to segregate the cache by assigning a "segment" to a set of related locations
@zandbelt I'm not sure whether we want to leave in the second part at all or just stick with the user-controlled configuration.
> try to avoid cache confusion

- AUTHORS
- README.md
- lib/resty/openidc.lua
- tests/spec/revoke_tokens_spec.lua
- tests/spec/test_support.lua
New function revoke_token() and revoke_tokens()
Enables the usage of revoke_token() for use cases which needs token revocation without logout.
> Make revoke_token() accessible

- AUTHORS
- lib/resty/openidc.lua
Calling bearer_jwt_verify fails because gsub is used incorrectly. This PR fixes the calls to gsub.
The error:
```
2022/04/22 07:18:01 [error] 9#9: *6 lua entry thread aborted: runtime error: /usr/local/openresty/lualib/resty/openidc.lua:1789: bad argument #3 to 'gsub' (string/function/table expected)
stack traceback:
coroutine 0:
[C]: in function 'gsub'
/usr/local/openresty/lualib/resty/openidc.lua:1789: in function 'get_jwt_verification_cache_prefix'
/usr/local/openresty/lualib/resty/openidc.lua:1799: in function 'get_cached_jwt_verification'
/usr/local/openresty/lualib/resty/openidc.lua:1817: in function 'jwt_verify'
/usr/local/openresty/lualib/resty/openidc.lua:1860: in function 'bearer_jwt_verify'
access_by_lua(nginx.conf:76):23: in main chunk, client: 172.17.0.1, server: , request: …
```
> Bug when calling bearer_jwt_verify with cache_segment

- tests/Dockerfile
This PR fixes the version of serpent to a working one (0.28). The latest version in luarocks seems to be broken currently.
> CI Tests: serpent version 0.28

- ChangeLog
- lib/resty/openidc.lua
- tests/spec/logout_spec.lua
> restrict zero-pixel image logout to actual image requests

- README.md
- lib/resty/openidc.lua
- lua-resty-openidc-1.7.6-3.rockspec
- tests/Dockerfile
- tests/spec/access_token_access_spec.lua
- tests/spec/bearer_token_verification_spec.lua
- tests/spec/introspection_spec.lua
- tests/spec/logout_spec.lua
- tests/spec/redirect_to_op_spec.lua
- tests/spec/test_support.lua
- tests/spec/token_request_spec.lua
- tests/spec/userinfo_spec.lua
Complete rework of #478, all issues of #478 should be addressed. Uses `session:set` and `session:get` to manipulate the session variables.
Tested by unit tests and on real-world project.
> Migrate lua-resty-session to 4.0.3 [tested, works]

- README.md
- lib/resty/openidc.lua
Right now every single introspection response which has `active` field not set to `true` is just rejected. In situation where there are multiple calls using the same expired/revoked/wrong token response from introspection endpoint could be cached for time set in `exp` field.
This change will allow to do so. By simple configuration in introspection service it will be possible to enable or not (by setting proper value to `exp` field) caching of responses for inactive tokens.
> Enable caching of negative introspection responses

- lib/resty/openidc.lua
This PR improves the `openidc_get_bearer_access_token` function by trimming whitespace from headers and ensuring proper validation of the extracted access token. (Fixes #537)
- Added a `trim` function to remove leading and trailing whitespace from headers before processing.
- Changed the validation check from `nil` to `""` since `header:sub(divider + 1)` always return a string.
- If the token is missing, it will be an empty string (`""`) rather than `nil`.
- This ensures invalid tokens are correctly identified.
These improvements enhance robustness and prevent potential issues with incorrectly formatted headers.
After these changes, the unit tests improved from 498 successes / 11 failures to 503 successes / 0 failures.
Before:
After:
> Incorrect Handling of Bearer Token with trailing space in openidc_get_bearer_access_token
